### ISSUE TITLE
How to setup and run this application on our system 

### ISSUE THREAD

**Issue by gouravsachdeva** [hisptz/dhis-2-touch#8]
Hello,
I wants to know that how to setup this application on our system and run this application on our localhost. i  did install npm. please tell me the further steps. how to install plugin's and all 
![capture_npm](https://cloud.githubusercontent.com/assets/24933333/24090953/bb17d4ac-0d6a-11e7-989c-407fb7dbec43.JPG)

**Comment by chingalo** [comment]
Have you passed through README.md file?

**Comment by gouravsachdeva** [comment]
where to run this command "sh installPlugins.sh". because i am not able to this command.

**Comment by chingalo** [comment]
Well, first clone repository, then  changes directory to cloned repository and run the above command to install all necessary plugins for the app

**Comment by gouravsachdeva** [comment]
on running this app i am getting following error. 


[16:14:24]  bundle failed: 'ChartModule' is not exported by node_modules\angular2-highcharts\index.js
            (imported by .tmp\app\app.module.js). For help fixing this error see https://github.com/rollup/rollup/wiki/T
roubleshooting#name-is-not-exported-by-module
[16:14:24]  ionic-app-script task: "build"
[16:14:24]  Error: 'ChartModule' is not exported by node_modules\angular2-highcharts\index.js (imported
            by .tmp\app\app.module.js). For help fixing this error see https://github.com/rollup/rollup/wiki/Troubleshoo
ting#name-is-not-exported-by-module

**Comment by chingalo** [comment]
Edit "node_modules/@ionic/app-scripts/config/rollup.config.js" inside cloned project
  
  find and replace commonjs(),  with codes below
  commonjs({
        namedExports: { 'node_modules/angular2-highcharts/index.js':['ChartModule']}
      }),

But all of these has been explained in Readme file.
