### ISSUE TITLE
Error : Cannot login!!

### ISSUE THREAD

**Issue by Sidhanshu28** [hisptz/dhis-2-touch#9]
When I run command 'ionic serve' , I get this app running on browser but whenever i try to log in, it gives me error : Please check the server URL.
through debugging I got to know that it's actually happening due to some cordova version. Is there any specific version compatibility?
Can you please tell me versions of node, npm, cordova and ionic, which are compatible ?
My versions are : 
node 6.9.5
npm 3.10.10
cordova 4.2.0
ionic 2.2.1

**Comment by chingalo** [comment]
Use either emulator or real device and not on browser.
